### ISSUE TITLE
Got into a loop of CPU busy, children timeout, new children killed immediately due to timeout

### ISSUE THREAD

**Issue by jayalane** [doublereedkurt/ufork#4]
In my copy, I'm going to have a separate timeout for "first health check" and make it more like 60 or 120 seconds.

**Comment by mahmoud** [comment]
Hey Chris! Are you saying that the wrong children were getting killed, or the new children were legitimately blocking on CPU loop?

**Comment by jayalane** [comment]
wrong children were not being killed.  loadavg was 40 on 4 cpu box and children were not running before getting killed (and consequently python process was occupying a large amount of CPU on the box for no gain -- symptom is getting paged due to "KMA is using 100% on boxes"

**Comment by jayalane** [comment]
Seems Kurt fixed this 2 years ago:  96e34eb  but never pulled it back.

**Comment by kurtbrose** [comment]
That's really weird, I thought that was added in response to drowning HSM
servers with TLS handshakes that they couldn't catch up with.

Maybe I made the change only in KMA or something?
